### PR TITLE
Fix storage of DOM elements

### PR DESCRIPTION
**Pull request by thecrypticace**
If you store a DOM element in a `value()` you may get errors from the browser or in more rare cases (explained in the commit message) an error during vnode patching.

The vnode patching error feels like something inside Vue is wrong for something like this to be able to cause that kind of error but I want to look more into it to see why that might be happening.

In any case this appears to fix the issue from what I can tell. I have not written a test for it yet, just a stub. I need to figure out how to write one that will verify the problem whether or not its run in a browser.

### CODE REVIEW

**Comment by beeplin** [comment]
Cool! I met this problem yesterday when using tiptap rich text editor.

**Comment by thecrypticace** [comment]
Oh good so I'm not completely crazy for trying to put a DOM element into an observed property.

🙌

**Comment by liximomo** [comment]
The default environment in Jest is `jsdom`, we don't need to install it again.

**Comment by beeplin** [comment]
Hi @liximomo, thank you for your efforts for the wonderful 2.2.0~  I am eager to try the new render function support ;) .

However,  just like what @thecrypticace shows above, when I am using tiptap (https://github.com/scrumpy/tiptap, probably the best rich text editor in
 Vue ecosystem) it breaks the whole vue runtime when emitting events under higher than 2.0.6, saying no el in vnode.

**Comment by thecrypticace** [comment]
Seeing as the new proposal has changed things a bit I'm closing this PR. This issue will need to be resolved in some manner in any case due to the introduction of template refs.

**Pull request closed without merging**
